config/routes.rb
Rails.application.routes.draw do
  devise_for :users
root to: 'users#index'

resources :users do
  resources :bookshelves
end

resources :bookshelves do
  resources :books
end

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user, dependent: :destroy
end

app/models/bookshelf.rb
class Bookshelf < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bookshelves, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # AM: You don't have any create or update actions? How can I go about adding/updating books?
  # AM: Please let me know if you would like help setting this up. This is definitely something we should hammer down before moving to far from Rails.
  def index
    @user = User.all
    @books = Book.where(params[:bookshelf_id])
  end

end

app/controllers/bookshelves_controller.rb
class BookshelvesController < ApplicationController
  # AM: You don't have any create or update actions? How can I go about adding/updating books?
  def index
    @user = User.find(params[:user_id])
    @books = Book.where(params[:bookshelf_id])
  end

  def show
    @user = User.find(params[:user_id])
    @bookshelves = @user.bookshelves
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    authenticate_user!
    @users = User.all
    @bookshelves = Bookshelf.all
  end

  def show
    @user = User.find(params[:id])
    @bookshelves = @user.bookshelves
      @books = Book.where(params[:bookshelf_id])
  end

  def new
  end

  def create
    @users = User.create!(name: params[:name], age: params[:age])
    render :index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.erb
<!-- <h1>Books Index</h1>
---------------------- -->

<section id: books>
<%= link_to image_tag('http://eloquentjavascript.net/1st_edition/img/ejs.png'), 'http://eloquentjavascript.net/Eloquent_JavaScript.pdf' %> <h1>Eloquent Javascript</h1>
<p>"JavaScript lies at the heart of almost every modern web application, from social apps to the newest browser-based games. Though simple for beginners to pick up and play with, JavaScript is a flexible, complex language that you can use to build full-scale applications.

Eloquent JavaScript, 2nd Edition dives deep into the JavaScript language to show you how to write beautiful, effective code. Author Marijn Haverbeke immerses you in example code from the start, while exercises and full-chapter projects give you hands-on experience with writing your own programs.</p>


<%= link_to image_tag('http://ecx.images-amazon.com/images/I/51qtp4NzjRL._SX258_BO1,204,203,200_.jpg'), 'http://www.infoq.com/resource/news/2009/01/The-Well-Grounded-Rubyist/en/resources/ch15black.pdf' %> <h1> The Well-Grounded Rubyist</h1>

<p>

The Well-Grounded Rubyist, Second Edition addresses both newcomers to Ruby as well as Ruby programmers who want to deepen their understanding of the language. This beautifully written and totally revised second edition includes coverage of features that are new in Ruby 2.1, as well as expanded and updated coverage of aspects of the language that have changed.
</p>

-----------------------

<h2><%= link_to "Home", root_path %></h2>

</section>

app/views/books/show.html.erb
<h1>Books Show Page</h1>
<!-- AM: Again, I would use CSS (or if need be, <hr>) to implement dividers. -->
-----------------------



<h3> <a href="/users/new">New Books</a> </h3>


-----------------------

<h2><%= link_to "Home", root_path %></h2>

app/views/bookshelves/index.html.erb
<!-- <h1>Bookshelves Index Page</h1>- -->

<h1>
  <ul>
  <% @books.each do |book| %>
    <ul>
      <%= link_to book.title, bookshelf_books_path(@user) %>
    </ul>
  <% end %>
  </ul>
</h1>

<!-- <h3> <a href="/books/new">New Books</a> </h3>
 -->

-----------------------

<h2><%= link_to "Home", root_path %></h2>

app/views/bookshelves/show.html.erb
<h1>Bookshelf Show Page</h1>
-----------------------

<h1>
  <% @books.each do |book| %>

    <%= link_to book.title, bookshelf_books(@bookshelves, book) %>

  <% end %>
</h1>

<h3> <a href="/books/new">New Books</a> </h3>


-----------------------

<h2><%= link_to "Home", root_path %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookshelf App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Logo -->
<div class="logo" >
  <%= image_tag("logo.png", :alt => "logo") %>
</div>

<% if current_user %>
  <h3><%= link_to 'Signout', destroy_user_session_path, :method => :delete %></h3>
<% else %>
  <h3><%= link_to 'Signup', new_user_registration_path %></h3>
  <h3><%= link_to 'Login', new_user_session_path %></h3>
<% end %>

<%= yield %>

</body>
</html>

app/views/layouts/users/index.html.erb
<h1>Hi</h1>

app/views/users/index.html.erb
<h1>
  <% @users.each do |user| %>
  <%= link_to user.email, user %>
  <% end %>
</h1>

app/views/users/new.html.erb
<form action="/users" method="post" >
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="name">Name:</label>
  <input name="name">

  <label for="age">Age:</label>
  <!-- The below attribute should be `name=`. You don't need to indicate data type here. -->
  <input integer="age">

  <input type="submit" value="Create">
</form>

app/views/users/show.html.erb
<!-- <h1>Users Show Page</h1> -->

<h1>
      <%= link_to "Bookshelf", bookshelf_books_path(@user) %>
</h1>



<!-- <h1>
  <% @bookshelves.each do |bookshelf| %>

  <%= link_to bookshelf.name, user_bookshelves_path(@user, bookshelf) %>

  <% end %>
</h1> -->

<!-- <h3> <a href="/bookshelves/new">New Bookshelf</a> </h3> -->
-----------------------

<h2><%= link_to "Home", root_path %></h2>